version = "0.4.0"
content_dir = "pages"

[[html.assets]]
css_stylesheet = "./style.css"
js_scripts = "./viewer.js"
copy = ["assets/**/*", "favicon.*"]

[pdf.spine]
title = "Historique des villages du Moyen Pays Niçois"
merge = true
vertebrae = [
    "frontmatter.typ",
    "avant-propos.typ",
    "vesubie.typ",
    "lantosque.typ",
    "lantosque_notables.typ",
    "lantosque_saint-colomban.typ",
    "luceram.typ",
    "luceram_peira-cava.typ",
]

[epub.spine]
title = "Historique des villages du Moyen Pays Niçois"
vertebrae = [
    "avant-propos.typ",
    "vesubie.typ",
    "lantosque.typ",
    "lantosque_notables.typ",
    "lantosque_saint-colomban.typ",
    "luceram.typ",
    "luceram_peira-cava.typ",
]
